### ISSUE TITLE
BR2 visualization

### ISSUE THREAD

**Issue by skim0119** [GazzolaLab/Blender-Soft-Rod#12]
Create example cases (either in documentation or part of package):
- [ ] Given the position of the center lines of three FREEs, the BR2 can be visualized. 
- [x] Given the position of the center line of the BR2 and centerline location of three rods, visualize all three. 

_Originally posted by @hanson-hschang in https://github.com/adikorlahalli/Blender-Soft-Arm-Simulation/issues/9#issuecomment-2143654354_

**Comment by hanson-hschang** [comment]
This is completed in the example in the commit dd5b83e.
