### ISSUE TITLE
Visualize director

### ISSUE THREAD

**Issue by skim0119** [GazzolaLab/Blender-Soft-Rod#13]

**Comment by hanson-hschang** [comment]
Might be something on the same direction. I am not testing twisting of my COBRA model, and it is hard to tell which direction it is twisting now. It might be better to have director to visualize twisting.

**Comment by hanson-hschang** [comment]
The BR2 visualization is done with the [example](https://github.com/GazzolaLab/Blender-Soft-Rod/tree/main/examples/br2) in the commit dd5b83e.

**Comment by hanson-hschang** [comment]
TODO: Add Pose example
