### ISSUE TITLE
Add detail documentation

### ISSUE THREAD

**Issue by Rohar10** [GazzolaLab/Blender-Soft-Rod#36]
Tutorial on docsting style guide: https://numpydoc.readthedocs.io/en/latest/format.html
some formatting example: https://www.datacamp.com/tutorial/docstrings-python

**Comment by hanson-hschang** [comment]
- geometry
    - composite
        - [ ] pose
        - [ ] rod
        - [ ] stack
    - primitives
        - [ ] simple: Sphere, Cylinder

**Comment by Rohar10** [comment]
Documentation has been made more thorough. We will review at the meeting today before committing any changes.
